use-sort:
    group:
        - _main
        - LIN3S
    group-type: each
    sort-type: alph
    sort-direction: asc

header: |
    /*
     * This file is part of the CHANGE-FOR-PROJECT-NAME project.
     *
     * Copyright (c) 2015 LIN3S <info@lin3s.com>
     *
     * For the full copyright and license information, please view the LICENSE
     * file that was distributed with this source code.
     */
